// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8nrx909fTuCnu2hblhr3_deg-ezHdPQ',
    appId: '1:988106397716:web:da5dd16f6ed38741c3ef01',
    messagingSenderId: '988106397716',
    projectId: 'woowfy-app',
    authDomain: 'woowfy-app.firebaseapp.com',
    storageBucket: 'woowfy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_ZbJll6CeLBr5S7nKOjZVn5sN3aa9aA',
    appId: '1:988106397716:android:db781f965bab44a7c3ef01',
    messagingSenderId: '988106397716',
    projectId: 'woowfy-app',
    storageBucket: 'woowfy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChca9sn9WwnMGmHi6GXb7QPrwGFDku98g',
    appId: '1:988106397716:ios:2068c23ea80599f4c3ef01',
    messagingSenderId: '988106397716',
    projectId: 'woowfy-app',
    storageBucket: 'woowfy-app.firebasestorage.app',
    iosBundleId: 'com.woowfy.woowfy',
  );
}
